// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tthk.ContactsRegistry.Data;

namespace tthk.ContactsRegistry.Migrations
{
    [DbContext(typeof(ContactsContext))]
    [Migration("20190227155412_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("tthk.ContactsRegistry.Data.ContactEasy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Initials");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumbers");

                    b.HasKey("Id");

                    b.ToTable("ContactEasies");
                });
#pragma warning restore 612, 618
        }
    }
}
